In [1]:
import numpy as np


In [2]:
arr=np.array([1500,3000,5000])
print(arr)

[1500 3000 5000]


In [3]:
arr2=np.array([[10,15,8,12],[5,7,4,6],[2,3,2,4]])
print(arr2)
print(arr2.ndim)
print(arr2.shape)


[[10 15  8 12]
 [ 5  7  4  6]
 [ 2  3  2  4]]
2
(3, 4)


In [6]:
print(arr2+2)


[[12 17 10 14]
 [ 7  9  6  8]
 [ 4  5  4  6]]


In [7]:
print(np.dot(arr,arr2))

[40000 58500 34000 56000]


In [8]:
print(np.sqrt(arr2))

[[3.16227766 3.87298335 2.82842712 3.46410162]
 [2.23606798 2.64575131 2.         2.44948974]
 [1.41421356 1.73205081 1.41421356 2.        ]]


Phase 3 Slicing and indexing

In [9]:
print(arr2[1,0:4])

[5 7 4 6]


In [12]:
print(arr2[:,:2])

[[10 15]
 [ 5  7]
 [ 2  3]]


In [13]:
print(arr2[2,3])

4


In [14]:
print(arr2[0:2,0:2])

[[10 15]
 [ 5  7]]


Phase 4 - Reshaping and Linespace.

In [16]:
print(np.reshape(arr2,(1,12)))
print(arr2.reshape(12))
print(np.reshape(arr2,(2,6)))
print(arr2.reshape(2,6))
print(np.linspace(0,100,12))

[[10 15  8 12  5  7  4  6  2  3  2  4]]
[10 15  8 12  5  7  4  6  2  3  2  4]
[[10 15  8 12  5  7]
 [ 4  6  2  3  2  4]]
[[10 15  8 12  5  7]
 [ 4  6  2  3  2  4]]
[  0.           9.09090909  18.18181818  27.27272727  36.36363636
  45.45454545  54.54545455  63.63636364  72.72727273  81.81818182
  90.90909091 100.        ]


Phase: 5 . The Random Module

In [20]:
print(np.random.randint(1,20,size=(3,4)))
print(np.random.rand(5))

[[11  3 16 14]
 [15 13  8  5]
 [ 1 12  6  2]]
[0.50811838 0.42057784 0.2272443  0.36516534 0.60440712]


In [23]:
print(np.sum(arr2))
print(np.sum(arr2,axis=0)) #To sum the columns
print(np.sum(arr2,axis=1)) #To sum the rows

78
[17 25 14 22]
[45 22 11]


In [ ]:
The dataset


In [60]:
marks=np.array([[78,85,90],[45,60,55],[88,92,95],[30,40,35],[65,70,75]])
print(marks)

[[78 85 90]
 [45 60 55]
 [88 92 95]
 [30 40 35]
 [65 70 75]]


In [61]:
print(marks.shape)
print(marks.size)
print(marks.dtype)


(5, 3)
15
int64


In [62]:
print(marks[1,0:3])
print(marks[:,2:])
print(marks[0,1])

[45 60 55]
[[90]
 [55]
 [95]
 [35]
 [75]]
85


Analysis


In [63]:
print(np.mean(marks,axis=0))
print(np.mean(marks,axis=1))
print(np.mean(marks[marks>=80]))
print(marks+5)

[61.2 69.4 70. ]
[84.33333333 53.33333333 91.66666667 35.         70.        ]
90.0
[[ 83  90  95]
 [ 50  65  60]
 [ 93  97 100]
 [ 35  45  40]
 [ 70  75  80]]


Conditional Logic


In [64]:
print(np.where(marks>=50,"1","0"))
print(np.where(marks<40,"0",marks))

[['1' '1' '1']
 ['0' '1' '1']
 ['1' '1' '1']
 ['0' '0' '0']
 ['1' '1' '1']]
[['78' '85' '90']
 ['45' '60' '55']
 ['88' '92' '95']
 ['0' '40' '0']
 ['65' '70' '75']]


Performance Scoring


In [65]:
av=np.mean(marks,axis=1)
print(av)
print(np.where(av>=85,"A",np.where(av>=70,"B",np.where(av>=50,"C","NO grade"))))

[84.33333333 53.33333333 91.66666667 35.         70.        ]
['B' 'C' 'A' 'NO grade' 'B']


Data Integrity


In [66]:
marks1=marks
print(marks1)
marks2=marks.copy()
print(marks2)



[[78 85 90]
 [45 60 55]
 [88 92 95]
 [30 40 35]
 [65 70 75]]
[[78 85 90]
 [45 60 55]
 [88 92 95]
 [30 40 35]
 [65 70 75]]


In [67]:
marks[0,0]=0
print(marks1)
print(marks2)

[[ 0 85 90]
 [45 60 55]
 [88 92 95]
 [30 40 35]
 [65 70 75]]
[[78 85 90]
 [45 60 55]
 [88 92 95]
 [30 40 35]
 [65 70 75]]


Array Creation & Inspection


In [ ]:
elect=np.random.randint(120,650,size=(5,4))

In [2]:
import numpy as np
arr1=np.random.randint(120,650,size=(4,7))
print(arr1)

[[274 563 264 437 434 223 467]
 [363 167 477 614 191 609 641]
 [449 139 383 429 637 219 534]
 [602 355 403 442 634 282 131]]


In [3]:
print(arr1.shape)
print(arr1.size)
print(arr1.dtype)
print(arr1.ndim)

(4, 7)
28
int32
2


In [ ]:
print(arr1.mean(axis=0))
print(np.max(arr1,axis=1))
print(np.min(arr1,axis=0))

[422.   306.   381.75 480.5  474.   333.25 443.25]
[380.28571429 437.42857143 398.57142857 407.        ]


In [6]:
avgperhos=np.mean(arr1,axis=1)
max_perhos=np.max(arr1,axis=1)
highest_perhos=np.max(avgperhos)
print(avgperhos)
print(max_perhos)
print(highest_perhos)

[380.28571429 437.42857143 398.57142857 407.        ]
[563 641 637 634]
437.42857142857144


In [7]:
total_per_day=np.sum(arr1,axis=0)
print(total_per_day)
highest_day=np.argmax(total_per_day)
print(highest_day)

[1688 1224 1527 1922 1896 1333 1773]
3


In [8]:
penalized_usage=np.where(arr1>500,arr1*1.20,arr1)
print(penalized_usage)

[[274.  675.6 264.  437.  434.  223.  467. ]
 [363.  167.  477.  736.8 191.  730.8 769.2]
 [449.  139.  383.  429.  764.4 219.  640.8]
 [722.4 355.  403.  442.  760.8 282.  131. ]]


In [9]:
hotel_avg_col=avgperhos[:,np.newaxis]
above_avg=arr1>hotel_avg_col
print(above_avg)

[[False  True False  True  True False  True]
 [False False  True  True False  True  True]
 [ True False False  True  True False  True]
 [ True False False  True  True False False]]


In [10]:
single_row=arr1.reshape(1,28)
print(single_row)

[[274 563 264 437 434 223 467 363 167 477 614 191 609 641 449 139 383 429
  637 219 534 602 355 403 442 634 282 131]]


In [11]:
two_rows=arr1.reshape(2,14)
print(two_rows)

[[274 563 264 437 434 223 467 363 167 477 614 191 609 641]
 [449 139 383 429 637 219 534 602 355 403 442 634 282 131]]


In [ ]:
electricity=np.random.randint(120,650,size=(4,7))
size=(4,7)
ref

In [ ]:
import numpy as np
